// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:alowonle_poultry_manager/data/daily_log_model.dart';
import 'package:alowonle_poultry_manager/data/inventory_item_model.dart';
import 'package:alowonle_poultry_manager/data/pen_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyLogAdapter());
    registerAdapter(InventoryItemAdapter());
    registerAdapter(PenAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyLogAdapter());
    registerAdapter(InventoryItemAdapter());
    registerAdapter(PenAdapter());
  }
}
